name: SimpleFlutterApp
description: A new flutter project.
dependencies:
  flutter:
    path: ../../flutter-sdk/packages/flutter
  intl: '>=0.12.4+2 <0.13.0'

dev_dependencies:
  test: any # flutter_test provides the version constraints
  flutter_test:
    path: ../../flutter-sdk/packages/flutter_test
  flutter_driver:
    path: ../../flutter-sdk/packages/flutter_driver
